/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        File gatesJs = new File("src/main/resources/gates.js");
        File noErrors = new File("src/main/resources/noErrors.js");
        File oneError = new File("src/main/resources/oneError.js");
        File fewErrors = new File("src/main/resources/fewErrors.js");
        File empty = new File("src/main/resources/empty.js");
//        jsLinter(gatesJs);
//        jsLinter(noErrors);
//        jsLinter(oneError);
//        jsLinter(fewErrors);
        jsLinter(empty);
    }


    // Write a method that reads a JavaScript file with a given Path,
    // and generates an error message whenever it finds a line that doesn’t end in a semi-colon.

    public static void jsLinter(File jsFile) {
        try {
            Scanner reader = new Scanner(jsFile);
            int lineNumber = 0;
            while (reader.hasNextLine()) {
                String lineOfCode = reader.nextLine();
                lineNumber++;
                if (!lineOfCode.contains("if") && !lineOfCode.contains("else") &&
                    !lineOfCode.endsWith("}") && !lineOfCode.endsWith("{") && !lineOfCode.isBlank()) {
                    if (!lineOfCode.endsWith(";")) {
                        System.out.println(String.format("Line %d: Missing semicolon", lineNumber));
                    }
                }
            }
        } catch (FileNotFoundException e) {
            System.out.println("JS file was not found");
        }

    }
}
